### ISSUE TITLE
CraftCMS v4 Compatibility

### ISSUE THREAD

**Issue by richhayler** [whoisjuan/craft-color-mixer#10]
Is CraftCMS v4 compatibility planned for this plugin or will it not be updated?

**Comment by engram-design** [comment]
Just to chime in here, we'd be happy to port this over to Craft 4 if you're not planning to do so. https://verbb.io/craft-3

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/color-mixer/releases/tag/3.0.0). Do note the [breaking changes](https://github.com/verbb/color-mixer#upgrading-from-v1v2)
