### ISSUE TITLE
FR: RGB to Hex

### ISSUE THREAD

**Issue by RobErskine** [whoisjuan/craft-color-mixer#2]
Hey there. I love this plugin. I would love the ability to convert from RGB to Hex. Is there any way we can convert the private function rgbToHex to a public function? 

https://github.com/whoisjuan/craft-color-mixer/blob/v1/src/twigextensions/CraftColorMixerTwigExtension.php#L363

If you're open to pull requests let me know and I can submit that and update the documentation! Thanks ;D

**Comment by whoisjuan** [comment]
Yeah! If you want, please send a PR and I will merge it! Cheers!

**Comment by engram-design** [comment]
We've revamped the color conversion filters to support converting from and to just about anything in [3.0.0](https://github.com/verbb/color-mixer/releases/tag/3.0.0)

For this, you can use `{{ 'rgb(255,0,255)' | toHex }}`

Check out the updated [docs](https://github.com/verbb/color-mixer#conversion) for more.
