### ISSUE TITLE
FR: HSL and RGB conversion to Hex

### ISSUE THREAD

**Issue by richhayler** [whoisjuan/craft-color-mixer#9]
Given that the plugin can convert hex values to both HSL and RGB, it would be great if there was a filter to convert HSL and RGB values back to Hex.

A specific use case is: Conversion of Hex to HSL to then manipulate the colour saturation value and then converting the resulting HSL back to Hex.

**Comment by engram-design** [comment]
We've revamped the color conversion filters to support converting from and to just about anything in [3.0.0](https://github.com/verbb/color-mixer/releases/tag/3.0.0)

For this, you can use `{{ 'rgb(255,0,255)' | toHex }}` `{{ 'hsl(300, 100%, 50%)' | toHex }}`

Check out the updated [docs](https://github.com/verbb/color-mixer#conversion) for more.
